 # Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UsedGoodsUpload' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UsedGoodsUpload
    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'
    pod 'SnapKit', '~> 5.0.0'
end
